config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'events#index'
  
  resources :events, except: :index  do
    resources :tickets
  end  
  get '/showevents', to: "events#show_events"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # user ||= User.new 
    # can :read , :all
    # if user.admin?
    #   can  :read, Event
        # Define abilities for the passed in user here. For example:
        # user ||= User.new # Guest user (not logged in)
    
        # if user.admin?
        #   can :manage, :all
        # else
        #   can :read, :all
        # end
        user ||= User.new # Guest user (not logged in)
        if user.admin?
          can :manage, :all     
        elsif user.moderator?
          can :read, Event
          can :update, Event
        else
          can :read, :all
          can [:show_events], Event
          # Define abilities for guest users here
        end
      # end
    end
  
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
 

  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :tickets
    belongs_to :user
    

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :event
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  
  enum role: { user:0, admin: 1, moderator: 2}

  has_many :events, dependent: :destroy
  has_many :tickets, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    rescue_from CanCan::AccessDenied do |exception|
        redirect_to(root_url, {:flash => { :error => exception.message }})
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    skip_before_action :verify_authenticity_token, only: [:destroy]

    before_action :authenticate_user!
    load_and_authorize_resource

        
    def index
      
    end

    def show

        @event = Event.find(params[:id])
        
    end
    def new
        @event = Event.new
    end
    def create
        
        @event = current_user.events.new(event_params)
        if @event.save!
          redirect_to events_path, notice: 'Event was successfully created.'
        else
          render :new
        end
    end
    def edit
        @event = Event.find(params[:id])
    end
    def update
        @event = Event.find(params[:id])
        if @event.update(event_params)
          redirect_to @event, notice: 'Event was successfully updated.'
        else
          render :edit
        end
      end
    
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to root_path, status: :see_other
  end

  def show_events
    @events = Event.all
  end


    
      

      
    private

    def event_params
      params.require(:event).permit(:name, :date, :location) # Adjusted to match your Event model attributes
    end
end

app/controllers/helpers/application_helper.rb
module ApplicationHelper
end

app/controllers/helpers/events_helper.rb
module EventsHelper
end

app/controllers/helpers/tickets_helper.rb
module TicketsHelper
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
    before_action :set_event
    before_action :authenticate_user!
  
    # GET /events/:event_id/tickets/new
    def new
      @ticket = @event.tickets.new
    end
  
    # POST /events/:event_id/tickets
    def create
      @ticket = @event.tickets.new(ticket_params)
  
      if @ticket.save
        redirect_to @event, notice: 'Ticket was successfully created.'
      else
        render :new
      end
    end
    
    def index
      @event = Event.find(params[:event_id])
      @tickets = @event.tickets
    end

  
    private
  
    def set_event
      @event = Event.find(params[:event_id])
    end
  
    def ticket_params
      params.require(:ticket).permit(:price, :status)
    end
  end
  

app/views/events/destroy.html.erb
<h1>Event Deleted</h1>
<p>The event has been successfully deleted.</p>

app/views/events/edit.html.erb
<%= form_with(model: @event) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_field :date %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <%= form.submit %>
<% end %>

app/views/events/index.html.erb
<nav class="navbar navbar-light" style="background-color: #ADD8E6;">
  <a class="navbar-brand text-purple" href="#">Current User - <%= current_user.email %></a>
  <%= link_to 'Events', showevents_path , class: "btn btn-primary text-purple" %>
  <%= link_to "Create Event", new_event_path, class: "btn btn-primary text-purple" %>
  <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete },class: "btn btn-primary text-purple" %>
</nav>
<div class="event-header"></div>

app/views/events/new.html.erb
<%= link_to "Back to Events", showevents_path , class: "btn btn-secondary" ,:remote => true %>
<pre> </pre>
<%= form_with(model: @event) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_field :date %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <%= form.submit %>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<p>Date: <%= @event.date %></p>
<p>Location: <%= @event.location %></p>
<%= link_to "Buy Ticket", new_event_ticket_path(@event) %>

<%= link_to 'Edit Event', edit_event_path(@event) %>

<%= link_to "Destroy", event_path(@event), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>

                  
<%= link_to 'Show Tickets',event_tickets_path(@event) %>

app/views/events/show_events.html.erb
<div class="container">
  <%= link_to "Back to Homepage", root_path, class: "btn btn-secondary mb-4" %>
  <h1>Events</h1>
  <ul class="list-group">
    <% @events.each do |event| %>
      <li class="list-group-item">
        <%= link_to event.name, event_path(event), class: "text-decoration-none text-dark fw-bold" %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventTicketingSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag 'custom_style' %>

  </head>
  

  <body>
  <body>
 

  <%= yield %>
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

</html>

app/views/tickets/index.html.erb
<h1>Tickets for <%= @event.name %></h1>
<ul>
  <% @tickets.each do |ticket| %>
    <li>
      Price: <%= ticket.price %>, Status: <%= ticket.status %>
    </li>
  <% end %>
</ul>

app/views/tickets/new.html.erb
<!-- app/views/tickets/new.html.erb -->
<h1>New Ticket</h1>

<%= form_with(model: [@event, @ticket]) do |form| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% @ticket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Ticket' %>
  </div>
<% end %>

app/views/tickets/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<%= link_to "Back to Event", event_path(@event) %>